version: "3.8"
services:
  
  database:
    container_name: pg-database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 7000:80
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  
  app:
    container_name: express-boilerplate
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: sh -c "npm run swagger-autogen && npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: always

volumes:
  postgres-data: